stages:
  - build
  - deploy

build:
  image: node:14
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - dist
  tags:
    - onlinebank-docker
  only:
    - master

deploy:
  image: alpine
  stage: deploy
  script:
    - apk add --no-cache rsync openssh
    - mkdir ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - rsync -e ssh -rav --delete $CI_PROJECT_DIR/dist/ $SSH_USER@$SSH_HOST:/var/www/onlinebank.$SSH_HOST/html
  tags:
    - onlinebank-docker
  only:
    - master
